// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7pkpJeluTg21bzw3HnB8z4lkc9QpL6U4',
    appId: '1:107775541064:web:3d17031bd0f2664e35fd7d',
    messagingSenderId: '107775541064',
    projectId: 'pdf-editor-2b696',
    authDomain: 'pdf-editor-2b696.firebaseapp.com',
    storageBucket: 'pdf-editor-2b696.firebasestorage.app',
    measurementId: 'G-Z19Y2723S8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPYGllLBqDHaJLBp3TAtVHamiDiaLgCJ0',
    appId: '1:107775541064:android:8e72ac73ef49ad2135fd7d',
    messagingSenderId: '107775541064',
    projectId: 'pdf-editor-2b696',
    storageBucket: 'pdf-editor-2b696.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkcGb0AC5HBA7j05bWdGd_chYTqm4Nny4',
    appId: '1:107775541064:ios:9e8a5256f38e5b3935fd7d',
    messagingSenderId: '107775541064',
    projectId: 'pdf-editor-2b696',
    storageBucket: 'pdf-editor-2b696.firebasestorage.app',
    iosBundleId: 'com.getkawai.pdfEditor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkcGb0AC5HBA7j05bWdGd_chYTqm4Nny4',
    appId: '1:107775541064:ios:9e8a5256f38e5b3935fd7d',
    messagingSenderId: '107775541064',
    projectId: 'pdf-editor-2b696',
    storageBucket: 'pdf-editor-2b696.firebasestorage.app',
    iosBundleId: 'com.getkawai.pdfEditor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7pkpJeluTg21bzw3HnB8z4lkc9QpL6U4',
    appId: '1:107775541064:web:de9493ba5de8641235fd7d',
    messagingSenderId: '107775541064',
    projectId: 'pdf-editor-2b696',
    authDomain: 'pdf-editor-2b696.firebaseapp.com',
    storageBucket: 'pdf-editor-2b696.firebasestorage.app',
    measurementId: 'G-4BMR0DYWH5',
  );
}
