import 'dart:typed_data';
import 'dart:ui' as ui;
import 'package:syncfusion_flutter_pdf/pdf.dart';
import 'pdf_tool.dart';
import '../llm/llm.dart';

/// Tool for AI-assisted PDF content generation
class AiPdfAssistantTool implements PdfTool {
  final LlmService _llmService;

  AiPdfAssistantTool() : _llmService = LlmService();

  @override
  String get id => 'ai_pdf_assistant';

  @override
  String get name => 'AI PDF Assistant';

  @override
  String get description => 'Generate PDF content using AI';

  @override
  String get iconName => 'Icons.smart_toy';

  @override
  Map<String, String> get parametersSchema => {};

  @override
  Future<bool> isAvailable() async {
    return await _llmService.initialize();
  }

  @override
  Future<PdfToolResult> execute(Map<String, dynamic> parameters) async {
    try {
      final String prompt = parameters['prompt'] as String? ?? '';
      final String? systemPrompt = parameters['systemPrompt'] as String?;
      final String? title = parameters['title'] as String?;
      final String? modelPath = parameters['modelPath'] as String?;

      if (prompt.isEmpty) {
        return PdfToolResult.failure('Prompt is required');
      }

      if (modelPath != null && modelPath.isNotEmpty) {
        // Backwards compatibility: ignore custom paths and always use FunctionGemma
      }

      final loaded = await _llmService.ensureFunctionGemmaModelLoaded();
      if (!loaded) {
        return PdfToolResult.failure(
          _llmService.lastError ?? 'Failed to load model',
        );
      }

      // Generate content using AI
      final request = LlmGenerationRequest(
        prompt: prompt,
        systemPrompt: systemPrompt,
        temperature: 0.7,
        maxTokens: 1024,
      );

      final response = await _llmService.generate(request);

      if (!response.isComplete || response.errorMessage != null) {
        return PdfToolResult.failure(
          response.errorMessage ?? 'AI generation failed',
        );
      }

      // Create PDF with generated content
      final PdfDocument document = PdfDocument();
      final PdfPage page = document.pages.add();
      final PdfGraphics graphics = page.graphics;

      double yOffset = 50;

      // Add title if provided
      if (title != null && title.isNotEmpty) {
        final PdfFont titleFont = PdfStandardFont(
          PdfFontFamily.helvetica,
          24,
          style: PdfFontStyle.bold,
        );
        graphics.drawString(
          title,
          titleFont,
          bounds: ui.Rect.fromLTWH(
            50,
            yOffset,
            page.graphics.clientSize.width - 100,
            50,
          ),
        );
        yOffset += 60;
      }

      // Add AI-generated content
      final PdfFont textFont = PdfStandardFont(PdfFontFamily.helvetica, 12);

      PdfTextElement(text: response.content, font: textFont).draw(
        page: page,
        bounds: ui.Rect.fromLTWH(
          50,
          yOffset,
          page.getClientSize().width - 100,
          page.getClientSize().height - yOffset - 50,
        ),
        format: PdfLayoutFormat(layoutType: PdfLayoutType.paginate),
      );

      // Add AI attribution
      final PdfFont smallFont = PdfStandardFont(
        PdfFontFamily.helvetica,
        8,
        style: PdfFontStyle.italic,
      );
      page.graphics.drawString(
        'Generated by AI Assistant',
        smallFont,
        bounds: ui.Rect.fromLTWH(
          50,
          page.getClientSize().height - 30,
          page.getClientSize().width - 100,
          20,
        ),
      );

      // Save the document
      final List<int> bytes = await document.save();
      document.dispose();

      return PdfToolResult.success(
        pdfData: Uint8List.fromList(bytes),
        metadata: {
          'pageCount': document.pages.count,
          'title': title,
          'tokensGenerated': response.tokensGenerated,
          'generationTime': response.duration.inMilliseconds,
        },
      );
    } catch (e) {
      return PdfToolResult.failure('Error: $e');
    }
  }
}

/// Tool for summarizing PDF content using AI
class SummarizePdfTool implements PdfTool {
  final LlmService _llmService;

  SummarizePdfTool() : _llmService = LlmService();

  @override
  String get id => 'summarize_pdf';

  @override
  String get name => 'Summarize PDF';

  @override
  String get description => 'Generate AI summary of PDF content';

  @override
  String get iconName => 'Icons.auto_awesome';

  @override
  Map<String, String> get parametersSchema => {};

  @override
  Future<bool> isAvailable() async {
    return await _llmService.initialize();
  }

  @override
  Future<PdfToolResult> execute(Map<String, dynamic> parameters) async {
    try {
      final Uint8List pdfData =
          parameters['pdfData'] as Uint8List? ?? Uint8List(0);
      final String summaryType =
          parameters['summaryType'] as String? ?? 'brief';

      if (pdfData.isEmpty) {
        return PdfToolResult.failure('PDF data is required');
      }

      if (!_llmService.isModelLoaded) {
        final loaded = await _llmService.ensureFunctionGemmaModelLoaded();
        if (!loaded) {
          return PdfToolResult.failure(
            _llmService.lastError ?? 'Failed to load model',
          );
        }
      }

      // Extract text from PDF
      final String extractedText = _extractTextFromPdf(pdfData);

      if (extractedText.isEmpty) {
        return PdfToolResult.failure('No text found in PDF');
      }

      // Create summary prompt
      final String prompt =
          'Please summarize the following text in a $summaryType manner:\n\n$extractedText';

      // Generate summary using AI
      final request = LlmGenerationRequest(
        prompt: prompt,
        systemPrompt: 'You are a helpful assistant that summarizes documents.',
        temperature: 0.5,
        maxTokens: 512,
      );

      final response = await _llmService.generate(request);

      if (!response.isComplete || response.errorMessage != null) {
        return PdfToolResult.failure(
          response.errorMessage ?? 'Summarization failed',
        );
      }

      // Create PDF with summary
      final PdfDocument document = PdfDocument();
      final PdfPage page = document.pages.add();
      final PdfGraphics graphics = page.graphics;

      // Add title
      final PdfFont titleFont = PdfStandardFont(
        PdfFontFamily.helvetica,
        20,
        style: PdfFontStyle.bold,
      );
      graphics.drawString(
        'PDF Summary',
        titleFont,
        bounds: ui.Rect.fromLTWH(
          50,
          50,
          page.graphics.clientSize.width - 100,
          40,
        ),
      );

      // Add summary
      final PdfFont textFont = PdfStandardFont(PdfFontFamily.helvetica, 12);
      PdfTextElement(text: response.content, font: textFont).draw(
        page: page,
        bounds: ui.Rect.fromLTWH(
          50,
          100,
          page.getClientSize().width - 100,
          page.getClientSize().height - 150,
        ),
        format: PdfLayoutFormat(layoutType: PdfLayoutType.paginate),
      );

      // Save the document
      final List<int> bytes = await document.save();
      document.dispose();

      return PdfToolResult.success(
        pdfData: Uint8List.fromList(bytes),
        metadata: {
          'pageCount': 1,
          'summaryType': summaryType,
          'originalTextLength': extractedText.length,
          'summaryLength': response.content.length,
        },
      );
    } catch (e) {
      return PdfToolResult.failure('Error: $e');
    }
  }

  String _extractTextFromPdf(Uint8List pdfData) {
    try {
      final document = PdfDocument(inputBytes: pdfData);
      final extractor = PdfTextExtractor(document);
      final String text = extractor.extractText();
      document.dispose();
      return text;
    } catch (e) {
      return '';
    }
  }
}
